name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Check
        run: pnpm exec biome ci .
      - name: Build libs
        run: pnpm build
      - name: Get playwright version
        run: echo "PLAYWRIGHT_VERSION=$(pnpm list @playwright/test | grep @playwright | sed 's/.*@//')" >> $GITHUB_ENV
      - name: Setup playwright
        uses: ./.github/actions/setup-playwright
        with:
          version: ${{ env.PLAYWRIGHT_VERSION }}
      - name: Tests
        run: pnpm test
